name: flmnn

channels:
  - conda-forge

dependencies:
  - python=3.12
  - pip
  - pip:
      - numpy==1.26.4
      - scipy==1.17.1
      - scikit-fda==0.10.1
      - tensorly==0.9.0
      - scikit-learn==1.7.2
      - metric-learn==0.7.0
      - multimethod<2
      - matplotlib
