#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Aug 15 14:46:29 2026

Generate simulated data

@author: shanghongxie
"""

import numpy as np
import itertools
from scipy.stats import ortho_group
from sklearn.cluster import KMeans
from skfda.representation.basis import BSpline, Tensor

def generate_dense_data(
    Ns,
    Ms,
    npc,
    Ntrain,
    Ntest,
    sigma2x=1,
    sigma2y=5,
    random_state=1,
    basis_order=4,
    eigenvalue_decay=0.5,
):
    """
    Generate dense multidimensional functional data for evaluating FLMNN.

    The data are generated from a set of randomly rotated orthonormal
    eigenfunctions constructed from a tensor-product B-spline basis.
    The first `npc` eigenfunctions are retained, with exponentially
    decaying eigenvalues. FPC scores are generated from the resulting
    covariance structure. Classification labels are generated by
    applying a random linear transformation to the FPC scores, adding
    noise, and clustering the transformed scores using K-means.

    Independent noisy training and test datasets are then sampled from
    the simulated population.

    Arguments:
        Ns: tuple or list of int
            Number of observation grid points in each functional
            dimension.

            For example:

                Ns = (10, 10, 64)

            gives a 3-dimensional functional domain with
            10 x 10 x 64 grid points.

        Ms: tuple or list of int
            Number of B-spline basis functions in each functional
            dimension.

            For example:

                Ms = (5, 5, 8)

        npc: int
            Number of functional principal components used to generate
            the simulated functional observations.

        Ntrain: int
            Number of training subjects to generate.

        Ntest: int
            Number of test subjects to generate.

        sigma2x: float, default=1
            Variance of the measurement noise added to the functional
            observations.

        sigma2y: float, default=5
            Variance of the noise added to the transformed FPC scores
            before K-means clustering is used to generate class labels.

        random_state: int, default=1
            Random seed used to make the simulation reproducible.

        basis_order: int, default=4
            Order of the B-spline basis.

        eigenvalue_decay: float, default=0.5
            Controls the exponential decay of the simulated eigenvalues.
            Eigenvalues are generated as

                exp(-eigenvalue_decay * k),

            for k = 0, ..., npc-1.

    Returns:
        data: dict
            Dictionary containing the simulated training and test data
            together with the true eigenfunctions, eigenvalues, FPC
            scores, class labels, and subject indices.

            The dictionary contains:

                Y_noisy:
                    Training noisy functional observations with shape
                    (n1, ..., nD, Ntrain).

                Y_true:
                    Training noise-free functional observations with
                    shape (n1, ..., nD, Ntrain).

                test_Y_noisy:
                    Test noisy functional observations with shape
                    (n1, ..., nD, Ntest).

                test_Y_true:
                    Test noise-free functional observations with shape
                    (n1, ..., nD, Ntest).

                true_eigenfunctions:
                    True normalized eigenfunctions with shape
                    (npc, n1, ..., nD).

                eigenvalues:
                    Simulated eigenvalues with shape (npc,).

                train_true_scores:
                    True FPC scores for the training subjects with
                    shape (Ntrain, npc).

                test_true_scores:
                    True FPC scores for the test subjects with
                    shape (Ntest, npc).

                trainlabel:
                    Training class labels.

                testlabel:
                    Test class labels.

                trainindex:
                    Indices of subjects selected for the training set.

                testindex:
                    Indices of subjects selected for the test set.

                bspline_basis:
                    List of marginal B-spline basis objects.

                xgrids:
                    List of marginal observation grids.
    """

    Ns = tuple(Ns)
    Ms = tuple(Ms)

    nmode = len(Ns)

    if len(Ms) != nmode:
        raise ValueError(
            f"Ns and Ms must have the same length. "
            f"Received {nmode} dimensions in Ns and {len(Ms)} in Ms."
        )

    if npc > np.prod(Ms):
        raise ValueError(
            f"npc={npc} cannot exceed the tensor-product basis dimension "
            f"{np.prod(Ms)}."
        )

    # Total simulated population
    Ntotal = Ntrain + Ntest

    # ----------------------------------------------------------
    # Construct marginal B-spline bases
    # ----------------------------------------------------------

    bspline_basis = [
        BSpline(n_basis=m, order=basis_order)
        for m in Ms
    ]

    # Construct grids on [0, 1]
    xgrids = [
        np.linspace(0, 1, n)
        for n in Ns
    ]

    # ----------------------------------------------------------
    # Construct tensor-product B-spline basis
    # ----------------------------------------------------------

    X = np.array(list(itertools.product(*xgrids)))

    tp_basis = Tensor(bspline_basis)

    J_tp = tp_basis.gram_matrix()

    Phi = np.squeeze(tp_basis.evaluate(X)).T

    # ----------------------------------------------------------
    # Whiten tensor-product basis with respect to L2 inner product
    # ----------------------------------------------------------

    s_tp, P_tp = np.linalg.eigh(J_tp)

    # Protect against numerical round-off
    s_tp = np.maximum(s_tp, 1e-12)

    Coefs = np.diag(np.sqrt(1.0 / s_tp)) @ P_tp.T

    # Random orthogonal rotation
    
    rng = np.random.default_rng(random_state)

    # Random orthogonal rotation
    Q = ortho_group.rvs(np.prod(Ms),
        random_state=rng)
    
    Coefs = Q @ Coefs

    # ----------------------------------------------------------
    # Construct true eigenfunctions
    # ----------------------------------------------------------

    eigenfunction_shape = tuple(Ns)

    true_eigenfunctions = np.zeros(
        (np.prod(Ms),) + eigenfunction_shape
    )

    for k in range(np.prod(Ms)):

        Psik = Phi @ Coefs[k, :]

        true_eigenfunctions[k, ...] = Psik.reshape(eigenfunction_shape)

    # ----------------------------------------------------------
    # Normalize eigenfunctions
    # ----------------------------------------------------------

    n_grid = np.prod(Ns)

    for k in range(true_eigenfunctions.shape[0]):

        norm = np.sqrt(
            np.sum(true_eigenfunctions[k, ...] ** 2) / n_grid
        )

        true_eigenfunctions[k, ...] /= norm

    # Retain only first npc eigenfunctions
    true_eigenfunctions = true_eigenfunctions[:npc, ...]

    # ----------------------------------------------------------
    # Generate eigenvalues
    # ----------------------------------------------------------

    eigenvalues = np.exp(
        -eigenvalue_decay * np.arange(npc)
    )

    # ----------------------------------------------------------
    # Generate population FPC scores
    # ----------------------------------------------------------

    true_scores = np.random.multivariate_normal(
        mean=np.zeros(npc),
        cov=np.diag(eigenvalues),
        size=Ntotal
    )

    # ----------------------------------------------------------
    # Generate noise-free functional observations
    # ----------------------------------------------------------

    Y = np.zeros(
        tuple(Ns) + (Ntotal,)
    )

    for i in range(Ntotal):

        for k in range(npc):

            Y[..., i] += (
                true_scores[i, k] * true_eigenfunctions[k, ...]
            )

    # ----------------------------------------------------------
    # Generate classification structure
    # ----------------------------------------------------------

    # # Same 10-dimensional random transformation used in the
    # # original simulation when npc = 10.
    # L = np.array([
    #     [-0.2397902,   0.63131818, -1.11162912, -0.98022878,
    #      -0.17905524,  0.46029518,  1.61843218, -0.81693445,
    #       1.78876613,  0.18528279],

    #     [-1.55413767, -1.84835558,  1.115104,    0.69004053,
    #      -0.52054225, -2.20518561, -1.93345289, -1.94681535,
    #       0.02310557,   1.44671855],

    #     [-0.82288603,  0.40276404,  0.56315219, -1.71408008,
    #       0.83871339, -2.15152756,  2.0965092,   0.16679325,
    #       0.01706557, -0.8766209],

    #     [1.19700444,   0.73990993, -0.36704262, -0.29006049,
    #      -1.54941203, -1.91472926, -0.64153327,  0.34046068,
    #       0.37470488,   1.5452182],

    #     [1.11571637, -0.66209335, -0.01976835, -0.01416881,
    #      -0.80173481,  2.16876047,  -0.65833591,  0.31041037,
    #      -1.61955871,  0.21832735],

    #     [0.69492811,  0.34499958,  0.1079911,  -0.60561276,
    #      -0.35810082,  0.0825991,   0.87856117, -1.25192036,
    #       0.33071195, -0.70030389],

    #     [0.56931307, -0.93243855, -1.03195413,  0.66396436,
    #       1.74505671, -1.11529266,  0.97084729, -0.80854985,
    #      -0.3381591, -2.47031512],

    #     [-2.11889185, -0.6909362, -0.70190931, -0.00347164,
    #       0.14608992,  0.7625622, -0.39675224,  0.77233866,
    #      -1.09475835,  0.66286345],

    #     [-0.6791643,  1.43436401,  1.74455579,  0.04714057,
    #      -0.94610697,  0.10355627, -1.32104284,  1.19157769,
    #       0.90178703, -0.36424951],

    #     [0.79537621, -0.34679112,  1.77549755, -1.39003834,
    #       0.14644048, -0.6120274,  -1.14156837,  2.10051323,
    #       0.46669627, -0.02196989]
    # ])
    
    
    L = rng.normal(size=(npc, npc))

    if npc != 10:
        raise ValueError(
            "The current classification mechanism uses a fixed "
            "10 x 10 matrix L and therefore requires npc=10."
        )

    # Transform the true FPC scores
    new_scores = true_scores @ L.T

    # Add classification noise
    score_error = np.random.normal(
        0,
        np.sqrt(sigma2y),
        size=new_scores.shape
    )

    new_scores = new_scores + score_error

    # Generate four clusters
    kmeans = KMeans(
        n_clusters=4,
        random_state=0,
        n_init="auto"
    )

    clusters = kmeans.fit(new_scores).labels_

    # Convert clusters to binary labels
    label = 1 * (clusters >= 2)

    # ----------------------------------------------------------
    # Split population into training and test observations
    # ----------------------------------------------------------

    if Ntrain + Ntest > Ntotal:
        raise ValueError(
            "Ntrain + Ntest cannot exceed the simulated population size."
        )

    indices = np.random.permutation(Ntotal)

    trainindex = indices[:Ntrain]
    testindex = indices[Ntrain:Ntrain + Ntest]

    # ----------------------------------------------------------
    # Extract training and test populations
    # ----------------------------------------------------------

    Y_train_true = Y[..., trainindex]
    Y_test_true = Y[..., testindex]

    train_true_scores = true_scores[trainindex, :]
    test_true_scores = true_scores[testindex, :]

    trainlabel = label[trainindex]
    testlabel = label[testindex]

    # ----------------------------------------------------------
    # Add measurement noise
    # ----------------------------------------------------------

    train_noise = np.random.normal(
        0,
        np.sqrt(sigma2x),
        size=Y_train_true.shape
    )

    test_noise = np.random.normal(
        0,
        np.sqrt(sigma2x),
        size=Y_test_true.shape
    )

    Y_train_noisy = Y_train_true + train_noise
    Y_test_noisy = Y_test_true + test_noise

    # ----------------------------------------------------------
    # Collect results
    # ----------------------------------------------------------

    data = {
        "Y_noisy": Y_train_noisy,
        "Y_true": Y_train_true,
        "test_Y_noisy": Y_test_noisy,
        "test_Y_true": Y_test_true,
        "true_eigenfunctions": true_eigenfunctions,
        "eigenvalues": eigenvalues,
        "train_true_scores": train_true_scores,
        "test_true_scores": test_true_scores,
        "trainlabel": trainlabel,
        "testlabel": testlabel,
        "trainindex": trainindex,
        "testindex": testindex,
        "bspline_basis": bspline_basis,
        "xgrids": xgrids,
    }

    return data



import numpy as np
from sklearn.cluster import KMeans


def generate_sparse_data(
    Ns,
    Ms,
    npc,
    Ntrain,
    Ntest,
    sigma2x=1,
    sigma2y=5,
    n_locations=20,
    random_state=1,
    basis_order=4,
    eigenvalue_decay=0.5,  
):
    """
    Generate training and test datasets for sparse and irregular multidimensional
    functional data simulation.


    Parameters
    ----------
    Ns : tuple or list of int
        Number of grid points along each functional dimension.

    Ms: tuple or list of int
        Number of B-spline basis functions in each functional
        dimension.

        For example:

            Ms = (5, 5, 8)

    npc: int
        Number of functional principal components used to generate
        the simulated functional observations.

    Ntrain : int
        Number of training subjects.

    Ntest : int
        Number of test subjects.

    sigma2x : float, default=1
        Variance of measurement noise added to the functional data.

    sigma2y : float, default=5
        Variance of noise added to the transformed FPC scores used
        to generate the class labels.

    n_locations : int, default=20
        Number of observed locations in the first two dimensions
        for each subject. The full third-dimensional trajectory is
        retained at each observed location.

    random_state : int, default=1
        Random seed used for reproducibility.
        
    basis_order: int, default=4
        Order of the B-spline basis.

    eigenvalue_decay: float, default=0.5
        Controls the exponential decay of the simulated eigenvalues.
        Eigenvalues are generated as

            exp(-eigenvalue_decay * k),

        for k = 0, ..., npc-1.    

    Returns
    -------
    data : dict
        Dictionary containing separate training and test datasets.

        Keys include:

        train_Y_true : ndarray
            Noise-free training functional data.

        train_Y_noisy : ndarray
            Noisy training functional data.

        test_Y_true : ndarray
            Noise-free test functional data.

        test_Y_noisy : ndarray
            Noisy test functional data.

        trainlabel : ndarray
            Training class labels.

        testlabel : ndarray
            Test class labels.

        train_true_scores : ndarray
            True FPC scores for training subjects.

        test_true_scores : ndarray
            True FPC scores for test subjects.

        true_eigenfunctions : ndarray
            True population eigenfunctions.

        eigenvalues : ndarray
            True population eigenvalues.

        train_sparse_Y : ndarray
            Sparse noisy training observations.

        test_sparse_Y : ndarray
            Sparse noisy test observations.

        train_mask : ndarray
            Training observation masks.

        test_mask : ndarray
            Test observation masks.

        train_sparse_indices : list
            Observed locations for training subjects.

        test_sparse_indices : list
            Observed locations for test subjects.

        train_indices : ndarray
            Indices of subjects assigned to the training set.

        test_indices : ndarray
            Indices of subjects assigned to the test set.
    """

    Ns = tuple(Ns)

    if len(Ns) != 3:
        raise ValueError(
            "The current sparse-data generator requires a 3D domain."
        )

    n1, n2, n3 = Ns
        
    # Total simulated population
    Ntotal = Ntrain + Ntest

    # ----------------------------------------------------------
    # Construct marginal B-spline bases
    # ----------------------------------------------------------
    
    Ms = tuple(Ms)

    if len(Ms) != len(Ns):
        raise ValueError(
        "Ms and Ns must have the same number of dimensions."
    )

    bspline_basis = [
        BSpline(n_basis=m, order=basis_order)
        for m in Ms
    ]

    # Construct grids on [0, 1]
    xgrids = [
        np.linspace(0, 1, n)
        for n in Ns
    ]

    # ----------------------------------------------------------
    # Construct tensor-product B-spline basis
    # ----------------------------------------------------------

    X = np.array(list(itertools.product(*xgrids)))

    tp_basis = Tensor(bspline_basis)

    J_tp = tp_basis.gram_matrix()

    Phi = np.squeeze(tp_basis.evaluate(X)).T

    # ----------------------------------------------------------
    # Whiten tensor-product basis with respect to L2 inner product
    # ----------------------------------------------------------

    s_tp, P_tp = np.linalg.eigh(J_tp)

    # Protect against numerical round-off
    s_tp = np.maximum(s_tp, 1e-12)

    Coefs = np.diag(np.sqrt(1.0 / s_tp)) @ P_tp.T
    
    rng = np.random.default_rng(random_state)

    # Random orthogonal rotation
    Q = ortho_group.rvs(np.prod(Ms),
        random_state=rng)
    
    Coefs = Q @ Coefs

    # ----------------------------------------------------------
    # Construct true eigenfunctions
    # ----------------------------------------------------------

    eigenfunction_shape = tuple(Ns)

    true_eigenfunctions = np.zeros(
        (np.prod(Ms),) + eigenfunction_shape
    )

    for k in range(np.prod(Ms)):

        Psik = Phi @ Coefs[k, :]

        true_eigenfunctions[k, ...] = Psik.reshape(eigenfunction_shape)

    # ----------------------------------------------------------
    # Normalize eigenfunctions
    # ----------------------------------------------------------

    n_grid = np.prod(Ns)

    for k in range(true_eigenfunctions.shape[0]):

        norm = np.sqrt(
            np.sum(true_eigenfunctions[k, ...] ** 2) / n_grid
        )

        true_eigenfunctions[k, ...] /= norm

    # Retain only first npc eigenfunctions
    true_eigenfunctions = true_eigenfunctions[:npc, ...]

    # ----------------------------------------------------------
    # Generate eigenvalues
    # ----------------------------------------------------------

    eigenvalues = np.exp(
        -eigenvalue_decay * np.arange(npc)
    )    

    if n_locations > n1 * n2:
        raise ValueError(
            "n_locations cannot exceed n1 * n2."
        )
        
    

    rng = np.random.default_rng(random_state)

    # ----------------------------------------------------------
    # Generate FPC scores for entire population
    # ----------------------------------------------------------

    true_scores = rng.multivariate_normal(
        mean=np.zeros(npc),
        cov=np.diag(eigenvalues),
        size=Ntotal,
    )

    # ----------------------------------------------------------
    # Generate dense noise-free functional observations
    # ----------------------------------------------------------

    Y_true = np.zeros(
        (n1, n2, n3, Ntotal),
        dtype=float,
    )

    for i in range(Ntotal):
        Y_true[..., i] = np.tensordot(
            true_scores[i, :],
            true_eigenfunctions,
            axes=(0, 0),
        )

    # ----------------------------------------------------------
    # Add functional measurement noise
    # ----------------------------------------------------------

    measurement_error = rng.normal(
        0,
        np.sqrt(sigma2x),
        size=Y_true.shape,
    )

    Y_noisy = Y_true + measurement_error

    # ----------------------------------------------------------
    # Generate class labels
    # ----------------------------------------------------------

    # L = np.array([
    #     [-0.2397902,  0.63131818, -1.11162912, -0.98022878,
    #      -0.17905524,  0.46029518,  1.61843218, -0.81693445,
    #       1.78876613,  0.18528279],

    #     [-1.55413767, -1.84835558,  1.115104,  0.69004053,
    #      -0.52054225, -2.20518561, -1.93345289, -1.94681535,
    #       0.02310557,  1.44671855],

    #     [-0.82288603,  0.40276404,  0.56315219, -1.71408008,
    #       0.83871339, -2.15152756,  2.0965092,  0.16679325,
    #       0.01706557, -0.8766209],

    #     [1.19700444,  0.73990993, -0.36704262, -0.29006049,
    #      -1.54941203, -1.91472926, -0.64153327,  0.34046068,
    #       0.37470488,  1.5452182],

    #     [1.11571637, -0.66209335, -0.01976835, -0.01416881,
    #      -0.80173481,  2.16876047, -0.65833591, 0.31041037,
    #      -1.61955871,  0.21832735],

    #     [0.69492811,  0.34499958,  0.1079911, -0.60561276,
    #      -0.35810082,  0.0825991,  0.87856117, -1.25192036,
    #       0.33071195, -0.70030389],

    #     [0.56931307, -0.93243855, -1.03195413, 0.66396436,
    #       1.74505671, -1.11529266, 0.97084729, -0.80854985,
    #      -0.3381591, -2.47031512],

    #     [-2.11889185, -0.6909362, -0.70190931, -0.00347164,
    #       0.14608992, 0.7625622, -0.39675224, 0.77233866,
    #      -1.09475835,  0.66286345],

    #     [-0.6791643,  1.43436401,  1.74455579,  0.04714057,
    #      -0.94610697,  0.10355627, -1.32104284,  1.19157769,
    #       0.90178703, -0.36424951],

    #     [0.79537621, -0.34679112,  1.77549755, -1.39003834,
    #       0.14644048, -0.6120274, -1.14156837,  2.10051323,
    #       0.46669627, -0.02196989],
    # ])
    
    
    L = rng.normal(size=(npc, npc))

    if npc != 10:
        raise ValueError(
            "The current label-generation mechanism requires npc=10."
        )

    transformed_scores = true_scores @ L.T

    label_noise = rng.normal(
        0,
        np.sqrt(sigma2y),
        size=transformed_scores.shape,
    )

    transformed_scores += label_noise

    # Generate four latent clusters, then convert to binary labels.
    kmeans = KMeans(
        n_clusters=4,
        random_state=random_state,
        n_init="auto",
    )

    clusters = kmeans.fit_predict(transformed_scores)

    labels = (clusters >= 2).astype(int)

    # ----------------------------------------------------------
    # Split subjects into training and test sets
    # ----------------------------------------------------------

    all_indices = rng.permutation(Ntotal)

    train_indices = all_indices[:Ntrain]
    test_indices = all_indices[Ntrain:]

    # ----------------------------------------------------------
    # Extract training and test data
    # ----------------------------------------------------------

    train_Y_true = Y_true[..., train_indices]
    test_Y_true = Y_true[..., test_indices]

    train_Y_noisy = Y_noisy[..., train_indices]
    test_Y_noisy = Y_noisy[..., test_indices]

    train_true_scores = true_scores[train_indices, :]
    test_true_scores = true_scores[test_indices, :]

    trainlabel = labels[train_indices]
    testlabel = labels[test_indices]

    # ----------------------------------------------------------
    # Generate sparse observations separately for train/test
    # ----------------------------------------------------------

    train_sparse_Y = np.full(
        train_Y_noisy.shape,
        np.nan,
        dtype=float,
    )

    test_sparse_Y = np.full(
        test_Y_noisy.shape,
        np.nan,
        dtype=float,
    )

    train_mask = np.zeros(
        (n1, n2, Ntrain),
        dtype=bool,
    )

    test_mask = np.zeros(
        (n1, n2, Ntest),
        dtype=bool,
    )

    train_sparse_indices = []
    test_sparse_indices = []

    total_locations = n1 * n2

    # Training sparse observations
    for i in range(Ntrain):

        flat_idx = rng.choice(
            total_locations,
            size=n_locations,
            replace=False,
        )

        idx1, idx2 = np.unravel_index(
            flat_idx,
            (n1, n2),
        )

        train_sparse_Y[idx1, idx2, :, i] = \
            train_Y_noisy[idx1, idx2, :, i]

        train_mask[idx1, idx2, i] = True

        train_sparse_indices.append(
            np.column_stack((idx1, idx2))
        )

    # Test sparse observations
    for i in range(Ntest):

        flat_idx = rng.choice(
            total_locations,
            size=n_locations,
            replace=False,
        )

        idx1, idx2 = np.unravel_index(
            flat_idx,
            (n1, n2),
        )

        test_sparse_Y[idx1, idx2, :, i] = \
            test_Y_noisy[idx1, idx2, :, i]

        test_mask[idx1, idx2, i] = True

        test_sparse_indices.append(
            np.column_stack((idx1, idx2))
        )

    return {
        "train_Y_true": train_Y_true,
        "train_Y_noisy": train_Y_noisy,
        "train_true_scores": train_true_scores,
        "trainlabel": trainlabel,
        "train_sparse_Y": train_sparse_Y,
        "train_mask": train_mask,
        "train_sparse_indices": train_sparse_indices,

        "test_Y_true": test_Y_true,
        "test_Y_noisy": test_Y_noisy,
        "test_true_scores": test_true_scores,
        "testlabel": testlabel,
        "test_sparse_Y": test_sparse_Y,
        "test_mask": test_mask,
        "test_sparse_indices": test_sparse_indices,

        "true_eigenfunctions": true_eigenfunctions,
        "eigenvalues": eigenvalues,

        "train_indices": train_indices,
        "test_indices": test_indices,
    }


from scipy.interpolate import griddata


def interpolate_sparse_data(
    sparse_Y,
    mask,
):
    """
    Interpolate sparse 3D functional data over the first two
    dimensions.

    For each subject and each value of the third functional
    dimension, missing observations are reconstructed using
    linear interpolation. Locations outside the convex hull of
    observed points are filled using nearest-neighbor interpolation.

    Parameters
    ----------
    sparse_Y : ndarray
        Sparse functional data with shape

            (n1, n2, n3, n_samples),

        with np.nan at unobserved locations.

    mask : ndarray of bool
        Observation mask with shape

            (n1, n2, n_samples).

    Returns
    -------
    Y_interp : ndarray
        Interpolated dense functional data with the same shape
        as sparse_Y.
    """

    sparse_Y = np.asarray(sparse_Y)

    if sparse_Y.ndim != 4:
        raise ValueError(
            "sparse_Y must have shape (n1, n2, n3, n_samples)."
        )

    n1, n2, n3, n_samples = sparse_Y.shape

    if mask.shape != (n1, n2, n_samples):
        raise ValueError(
            "mask must have shape (n1, n2, n_samples)."
        )

    # Full grid in dimensions 1 and 2
    grid_x, grid_y = np.meshgrid(
        np.arange(n1),
        np.arange(n2),
        indexing="ij",
    )

    full_points = np.column_stack([
        grid_x.ravel(),
        grid_y.ravel(),
    ])

    Y_interp = np.empty_like(
        sparse_Y,
        dtype=float,
    )

    for i in range(n_samples):

        observed_mask = mask[:, :, i]

        observed_points = np.column_stack(
            np.where(observed_mask)
        )

        for k in range(n3):

            observed_values = sparse_Y[
                :, :, k, i
            ][observed_mask]

            # Linear interpolation
            interp_values = griddata(
                points=observed_points,
                values=observed_values,
                xi=full_points,
                method="linear",
            )

            # Outside the convex hull:
            # use nearest-neighbor interpolation
            missing = np.isnan(interp_values)

            if np.any(missing):

                nearest_values = griddata(
                    points=observed_points,
                    values=observed_values,
                    xi=full_points,
                    method="nearest",
                )

                interp_values[missing] = nearest_values[missing]

            Y_interp[:, :, k, i] = interp_values.reshape(
                n1,
                n2,
            )

    return Y_interp
